basePath: /
definitions:
  skills.ManyItemResponse:
    properties:
      limit:
        type: integer
      skills:
        items:
          $ref: '#/definitions/skills.Node'
        type: array
    type: object
  skills.Node:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: nexters@kakao.com
    name: API Support
    url: https://github.com/myungjin-likes-tuna/checkareer-core-go/issues
  description: todolist API
  title: todolist API
  version: 21.0.0
paths:
  /v1/skills:
    get:
      description: skills get
      operationId: skills-get
      parameters:
      - in: query
        minimum: 1
        name: id
        type: integer
      - default: 25
        example: 25
        in: query
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/skills.ManyItemResponse'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: skills get
      tags:
      - skills
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
